[package]
name = "rpkg-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hitman-xtea = { path = "./src/libs/hitman-xtea" }
binrw = "0.11.1"
modular-bitfield = "0.11.2"
memmap2 = "0.7.1"
regex = "1.7.1"
anyhow = "1.0.69"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.104"
rayon = "1.7.0"
md5 = "0.7.0"
