[package]
name = "rpkg-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.11.2"
modular-bitfield = "0.11.2"
memmap2 = "0.7.1"
rayon = "1.7.0"
regex = "1.9.5"
serde = { version = "1.0.188", features = ["derive"], optional = true }
lz4 = "1.24.0"
pathdiff = "0.2.1"

serde_json = { version = "1.0.107", optional = true }
itertools = { version = "0.12.0", features = [] }
thiserror = "1.0.56"
md-5 = "0.10.6"
extended-tea = "0.1.1"
byteorder = "1.5.0"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]
