[package]
name = "rpkg-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Parse Glacier ResourcePackage (rpkg) files, allowing access to the resources stored within."
repository = "https://github.com/dafitius/rpkg-rs"
readme = "README.md"

[dependencies]
binrw = "0.13.3"
modular-bitfield = "0.11.2"
memmap2 = "0.9.4"
rayon = "1.10.0"
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"], optional = true }
lz4 = "1.24.0"
pathdiff = "0.2.1"

serde_json = { version = "1.0.115", optional = true }
itertools = { version = "0.12.1", features = [] }
thiserror = "1.0.58"
md-5 = "0.10.6"
extended-tea = "0.1.1"
byteorder = "1.5.0"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]
