[package]
name = "rpkg-rs"
version = "0.1.5"
edition = "2021"
license = "Apache-2.0"
description = "Parse Glacier ResourcePackage (rpkg) files, allowing access to the resources stored within."
repository = "https://github.com/dafitius/rpkg-rs"
readme = "README.md"

[badges.maintenance]
status = "actively-developed"

[dependencies]
binrw = "0.13.3"
modular-bitfield = "0.11.2"
memmap2 = "0.9.4"
regex = "1.10.4"
lz4 = "1.24.0"
pathdiff = "0.2.1"

itertools = { version = "0.12.1", features = [] }
thiserror = "1.0.59"
md-5 = "0.10.6"

extended-tea = "0.1.1"
byteorder = "1.5.0"

rayon = { version = "1.10.0", optional = true}

[features]
path-list = ["dep:rayon"]

[dev-dependencies]
version-sync = "0.9.5"

