[package]
name = "rpkg-rs"
version = "0.1.0"
edition = "2021"

[[example]]
name = "print_packagedefs"

[[example]]
name = "extract_resource"

[dependencies]
hitman-xtea = { path = "./src/libs/hitman-xtea" }
binrw = "0.11.2"
modular-bitfield = "0.11.2"
memmap2 = "0.7.1"
rayon = "1.7.0"
md5 = "0.7.0"
regex = "1.9.5"
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"], optional = true }
lz4 = "1.24.0"
pathdiff = "0.2.1"

serde_json = { version = "1.0.107", optional = true }
itertools = { version = "0.12.0", features = [] }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]